name: "[Doc][M] Publish"

on:
  workflow_dispatch:

env:
  GH_JAVA_VERSION: "11"
  GH_SCALA_BINARY_VERSION: "2.12"
  GH_JAVA_DISTRIBUTION: "temurin"
  GH_JAVA_OPTS: "-Xss64m -Xms1024m -Xmx8G -XX:MaxMetaspaceSize=2G -XX:MaxInlineLevel=18"

jobs:
  build_and_publish_doc_site:
    if: github.ref != 'refs/heads/gh-pages' && github.ref != 'gh-pages'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { binary-version: "2.12", java-version: "11", java-distribution: "temurin" }
        node:
          - { version: "24.12.0" }

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ env.GH_JAVA_VERSION }}
          distribution: ${{ env.GH_JAVA_DISTRIBUTION }}
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build and publish website
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          GA_ANONYMIZE_IP: ${{ secrets.GA_ANONYMIZE_IP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_OPTS: ${{ env.GH_JAVA_OPTS }}
          JVM_OPTS: ${{ env.GH_JAVA_OPTS }}
          SBT_OPTS: ${{ env.GH_JAVA_OPTS }}
        run: |
          echo "JAVA_OPTS=${JAVA_OPTS}"
          echo " JVM_OPTS=${JVM_OPTS}"
          echo " SBT_OPTS=${SBT_OPTS}"
          
          sbt \
            gitHubPagesCreateGitHubPagesBranchIfNotExist \
            clean \
            writeCurrentVersion \
            docusaurGenerateAlgoliaConfigFile \
            docusaurGenerateGoogleAnalyticsConfigFile \
            docusaurInstall \
            docusaurCleanBuild \
            docusaurBuild \
            publishToGitHubPages
