name: "[Doc][A] Build Only"

on:
  push:
    branches:
      - "**"

jobs:
  build-docusaurus:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { binary-version: "2.12", java-version: "adopt@1.11" }
        node:
          - { version: "22.19.0" }

    steps:
      - uses: actions/checkout@v6
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.scala.java-version }}
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache SBT
        uses: actions/cache@v5
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

      - name: Cache npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build and publish website
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          GA_ANONYMIZE_IP: ${{ secrets.GA_ANONYMIZE_IP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt clean \
            writeCurrentVersion \
            docusaurGenerateAlgoliaConfigFile \
            docusaurGenerateGoogleAnalyticsConfigFile \
            docusaurInstall \
            docusaurCleanBuild \
            docusaurBuild
