name: "[Doc][M] Publish"

on:
  workflow_dispatch:

jobs:
  build_and_publish_doc_site:
    if: github.ref != 'refs/heads/gh-pages' && github.ref != 'gh-pages'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { binary-version: "2.12", java-version: "adopt@1.11" }

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.scala.java-version }}
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: '14.4.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build and publish website
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt clean \
            docusaurGenerateAlgoliaConfigFile \
            docusaurGenerateGoogleAnalyticsConfigFile \
            docusaurInstall \
            docusaurAuditFix \
            docusaurCleanBuild \
            docusaurBuild \
            publishToGitHubPages
